### ISSUE TITLE
Partials

### ISSUE THREAD

**Issue by jakobrosenberg** [weizhenye/rollup-plugin-bundle-scss#1]
Hi, does this project work with partials?

**Comment by weizhenye** [comment]
Yes, it should work.
It uses https://github.com/reactway/scss-bundle to bundle files, partials are [tested](https://github.com/reactway/scss-bundle/tree/dev/tests/cases/partial).

**Comment by weizhenye** [comment]
@jakobrosenberg Any problem?

**Comment by jakobrosenberg** [comment]
Sorry, I opened it but forgot to write. No I think it was working fine. I had mistakenly thought the project compiled to css.
