### ISSUE TITLE
Plugin does not support the `rootDir` scss-bundler flag

### ISSUE THREAD

**Issue by ImpendingDoom28** [weizhenye/rollup-plugin-bundle-scss#10]
Hello  @weizhenye ! As I can tell by looking through the code, it seems to me that this plugin does not support the `rootDir` option which comes from `scss-bundler`:

```js
 const {
    project = null,
    dedupeGlobs = [],
    includePaths = [],
    ignoreImports = [],
  } = bundlerOptions;
```

Without it I can't specify the only dir that this plugin should look inside for `*.scss` files and it just scans my full project and adds scss which I don't want to add. Could please you help with this issue?

**Comment by weizhenye** [comment]
`rootDir` is only work in [CLI Usage](https://github.com/reactway/scss-bundle#cli-usage) of `scss-bundle`, there is no support for `rootDir` with [Non-CLI usage](https://github.com/reactway/scss-bundle/blob/dev/src/bundler.ts#L26-L29).

You should import the scss files you need in `input` option, it scans files by imports, not folders.

**Comment by ImpendingDoom28** [comment]
@weizhenye I finally had time to look into that, I'm pretty new to rollup and some things are not that easily understandable for me rn. So I tried what you suggested, and I have this config:
```js
const config = defineConfig({
  input: ["src/index.ts", "src/assets/styles/variables.scss"],
  output: [
    {
      dir: "./dist",
      format: "es",
      exports: "named",
      sourcemap: debug
    },
    {
      dir: "./dist",
      sourcemap: debug,
      plugins: [
        bundleScss({ 
          bundlerOptions: {
            dedupeGlobs: ["./src/assets/styles/variables.scss"]
          }
        }),
      ],
    },
  ],
  external: [
    "react", 
    "react-is", 
    "react-router", 
    "react/jsx-runtime"
  ],
  plugins: [
    external(),
    scss({
      failOnError: true,
      insert: true,
      verbose: debug,
    }),
    url(),
    svgr({
      svgo: false,
    }),
    image(),
    resolve(),
    commonjs({
      include: /node_modules/,
      namedExports: {
        "react-dom": ["createPortal", "findDOMNode", "flushSync"],
        "node_modules/lodash/lodash.js": ["debounce"],
      },
    }),
    typescript({
      useTsconfigDeclarationDir: true,
      rollupCommonJSResolveHack: true,
      clean: true,
    }),
    !debug && terser()
  ],
});
```

As you can see, I used `import` you mentioned before, then I tried to use your plugin as an output plugin, but I keep getting this error:
`The "transform" hook used by the output plugin bundle-scss is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.`

What I'm doing wrong, any suggestions on that?

**Comment by weizhenye** [comment]
Try this:

```js
const config = defineConfig({
  input: ["src/index.ts", "src/assets/styles/variables.scss"],
  output: {
    dir: "./dist",
    format: "es",
    exports: "named",
    sourcemap: debug
  },
  // ...
  plugins: [
    external(),
    bundleScss({ 
      exclusive: false,
      bundlerOptions: {
        dedupeGlobs: ["./src/assets/styles/variables.scss"]
      }
    }),
    scss({
      failOnError: true,
      insert: true,
      verbose: debug,
    }),
    // ...
  ],
});
```

**Comment by ImpendingDoom28** [comment]
When I do it this way, I get the scss file with all scss from all my scss files, but I only want specific scss to be extracted to separate file (e.g. mixins and variables)

**Comment by weizhenye** [comment]
Maybe you should export an array from rollup.config.js

```js
export default [
  {
    input: "src/assets/styles/variables.scss",
    output: {
      dir: "./dist",
      sourcemap: debug
    },
    plugins: [
      bundleScss(),
    ]
  },
  {
    input: "src/index.ts",
    output: {
      dir: "./dist",
      format: "es",
      exports: "named",
      sourcemap: debug
    },
    plugins: [
      // ...
    ],
  }
];
```

**Comment by ImpendingDoom28** [comment]
@weizhenye After little tweaks with array config, this worked like a charm, thank you for your help and support!!
