### ISSUE TITLE
Odd SCSS output

### ISSUE THREAD

**Issue by androdel** [weizhenye/rollup-plugin-bundle-scss#3]
I have the following files:
src/_variables.scss
```
$red: #ff0000;
```

src/components/Dummy/style.module.scss
```
// Style Dummy
@import "../../variables";

.element {
    color: $red;
}
```

The CSS that's get build (looks good):
```
.d691d395a9b5453de31a3f684e897008{color:red}
```
The SCSS on the other hand:
```
export default {"element":"d691d395a9b5453de31a3f684e897008"};
```

**Comment by weizhenye** [comment]
It seems your SCSS file is transformed by postcss before it passed to `bundle-scss`.

But if we put `bundle-scss` before postcss, then postcss will not get the correct SCSS file.

Maybe I should add a option whether keep SCSS file untouched for post-process.

**Comment by weizhenye** [comment]
`exclusive` option is added in `v0.1.1`, set it to false and put `bundleScss()` before `postcss()`.

README is updated with a PostCSS example, please check it out.
