### ISSUE TITLE
Support passing optons to scss-bundle

### ISSUE THREAD

**Issue by jaybeeuu** [weizhenye/rollup-plugin-bundle-scss#4]
This is a really useful tool, however it would be even more useful if I could pass options down to `scss-bundle`.

For example I need to resolve `scss` files in `node_modules` and `../../mode_modules`, which i can do with `scss-bundle` using the [includePaths](https://github.com/reactway/scss-bundle#configuration) option, If i could pass this into your rollup plugin and have it pass it on to `scss-bundle` that would greatly increase the flexibility of your tool.

It looks like doing so would just be extending your call to [`bundler.bundle`](https://github.com/weizhenye/rollup-plugin-bundle-scss/blob/master/index.js#L40) along the lines of the call in the `scss-bundle` [cli script](https://github.com/reactway/scss-bundle/blob/dev/src/cli/main.ts#L51).

I would be happy to submit a PR if you accept the premise?

**Comment by weizhenye** [comment]
Path resolve should work out of the box if you import SCSS files in JS or SCSS explicitly, and I think `includePaths` option is only used for CLI. When using with Node API, all files as FileRegistry is passed to `scss-bundle`, and `includePaths` should be unnecessary.

**Comment by jaybeeuu** [comment]
That makea sense but I have a `scss` file with some global styles & imports in it though so I'm not importing them from a JS file. i.e. i am importing `scss` from `scss`. This is a whole thing different entry point in my library so i don't want to mention it in any of my `js` files.

Without `includePaths` it does work fine for relative imports, but the imports from `node_modules` are left in place  and i get comments in the output about unresolved imports. If i manually patch your plugin in my node_module then it resolves every thing nicely.

I can't show you the actual as it's prorietary, but I'll try and create a repro tonight.

**Comment by weizhenye** [comment]
`bundlerOptions` option is added in `v0.1.2`
