### ISSUE TITLE
Disable Styles and only bundle scss

### ISSUE THREAD

**Issue by areindl** [weizhenye/rollup-plugin-bundle-scss#6]
Hi! 

First of all I want to say thank you! Your plugin works great. The bundling is perfect.

I am using `plugin-rollup-vue` and since I am bundling the scss already with your plugin, I don't need styles at all. Do you have a clue on how to achieve this and disable the style-handling?

Thanks in advance.
Anton

**Comment by weizhenye** [comment]
Do you mean you don't want output the CSS file? Example in README should achieve this by default.

**Comment by areindl** [comment]
Hi @weizhenye, thanks for the reply. I tried the example number two (`Using with rollup-plugin-vue`) but the CSS was still inlined in the JS code of my components. I only want the bundled scss and no css at all in the esm-module.

 Should I provide an example?

**Comment by weizhenye** [comment]
Inlined CSS in JS is created by `rollup-plugin-vue` with option `{ css: true }`, you can set it to `false` and add another plugin to handle CSS files.

```js
import commonjs from 'rollup-plugin-commonjs';
import vue from 'rollup-plugin-vue';
import bundleScss from 'rollup-plugin-bundle-scss';
import css from 'rollup-plugin-css-only';

export default {
  // ...
  plugins: [
    commonjs(),
    bundleScss(),
    vue({ css: false }),
    css({ output: false }),
  ],
};

```

**Comment by areindl** [comment]
Thank you, @weizhenye. This worked and solved the problem.


Thanks and have a great day!
