### ISSUE TITLE
Support Vue 3

### ISSUE THREAD

**Issue by MechJosh0** [weizhenye/rollup-plugin-bundle-scss#7]
Upgrading to `rollup-plugin-vue^6.0.0` will support Vue 3. Currently, I'm unable to build my Vue 3 due to mismatch configurations coming from this package.

**Comment by weizhenye** [comment]
`rollup-plugin-vue@6` changes its behavior and will not handle styles by default.
So just put `bundleScss()` after `vue()`, it will work.

```js
import bundleScss from 'rollup-plugin-bundle-scss';
import vue from 'rollup-plugin-vue';

export default {
  input: 'src/App.vue',
  output: {
    file: 'dist/index.js',
    format: 'esm',
  },
  plugins: [
    vue(),
    // put it after vue()
    bundleScss(),
  ],
};
```

**Comment by MechJosh0** [comment]
Thanks for looking into it.

I'm still having the same conflict, please check out my branch which reproduces the issue: https://github.com/MechJosh0/bug--rollup-plugin-bundle-scss-v3-misatch

The reason you're not reproducing the issue is that I (and so will everyone else) have Vue installed in the project. In my repo, if you were to remove Vue as a dependency it'll build successfully.

Vue3 is throwing the error because `vue-template-compiler` is installed from your dependency list and Vue3 doesn't want it installed at all. The solution, which other packages have gone for is a major version upgrade (due to Vue version breaking change) and switched the dependency from `vue-template-compiler`  to `@vue/compiler-sfc` to be able to switch from supporting Vue2 to Vue3.

I'm unsure if you'll be able to support both at the same time.

**Comment by weizhenye** [comment]
`v0.1.3` is published. `vue-template-compiler` imported by `rollup-plugin-bundle-scss` will not throw error when Vue version is mismatch.

**Comment by MechJosh0** [comment]
Brilliant, thanks!

And I guess you can support both versions 👍
