### ISSUE TITLE
Plugin includes snippets multiple times when imported multiple times

### ISSUE THREAD

**Issue by janis-me** [weizhenye/rollup-plugin-bundle-scss#9]
Hey! first of all, thank you for making this!

I have a question about how stuff is bundled, because I ran into an "issue" while using:
When you import some .scss file in multiple other .scss files, for example some `variables.scss` file, the variables are included multiple times in the "final" scss build. Is this intentional?
I would expect that the plugin includes every file that was imported/used only once.

Thanks and have a great day!

// Edit

same thing if I use `@use` instead of `@import`

**Comment by weizhenye** [comment]
It uses [scss-bundle](https://github.com/reactway/scss-bundle) internally, I guess the option `dedupeGlobs` can solve your issue.

**Comment by janis-me** [comment]
It did! Thank you, and sorry I did not see that in the readme.
